// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3qsHqfvnlyTpgUVsAFFBbNg2ATxEFLc',
    appId: '1:167096627109:web:167f726e4952a1905d024c',
    messagingSenderId: '167096627109',
    projectId: 'quickconnect-3e930',
    authDomain: 'quickconnect-3e930.firebaseapp.com',
    storageBucket: 'quickconnect-3e930.appspot.com',
    measurementId: 'G-Y96WVCLCYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntpszA9oURJVaiVgeNuGHYbpLkOUvTaw',
    appId: '1:167096627109:android:d345fce84307adb95d024c',
    messagingSenderId: '167096627109',
    projectId: 'quickconnect-3e930',
    storageBucket: 'quickconnect-3e930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq8fnIP_7FTzDDjdDFWLE-hs89sHN9WfU',
    appId: '1:167096627109:ios:1d326e6331ab36365d024c',
    messagingSenderId: '167096627109',
    projectId: 'quickconnect-3e930',
    storageBucket: 'quickconnect-3e930.appspot.com',
    iosBundleId: 'com.example.quickConnectApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq8fnIP_7FTzDDjdDFWLE-hs89sHN9WfU',
    appId: '1:167096627109:ios:1d326e6331ab36365d024c',
    messagingSenderId: '167096627109',
    projectId: 'quickconnect-3e930',
    storageBucket: 'quickconnect-3e930.appspot.com',
    iosBundleId: 'com.example.quickConnectApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx3qsHqfvnlyTpgUVsAFFBbNg2ATxEFLc',
    appId: '1:167096627109:web:239158a11dad086e5d024c',
    messagingSenderId: '167096627109',
    projectId: 'quickconnect-3e930',
    authDomain: 'quickconnect-3e930.firebaseapp.com',
    storageBucket: 'quickconnect-3e930.appspot.com',
    measurementId: 'G-W6VCL9MVRJ',
  );
}
